export const races = [
  'Asian or Asian British',
  'Indian',
  'Pakistani',
  'Bangladeshi',
  'Chinese',
  'Any other Asian background',
  'Black, Black British, Caribbean or African',
  'Caribbean',
  'African',
  'Any other Black, Black British, or Caribbean background',
  'Mixed or multiple ethnic groups',
  'White and Black Caribbean',
  'White and Black African',
  'White and Asian',
  'Any other Mixed or multiple ethnic background',
  'White',
  'English, Welsh, Scottish, Northern Irish or British',
  'Irish',
  'Gypsy or Irish Traveller',
  'Roma',
  'Any other White background',
  'Other ethnic group',
  'Arab',
  'Any other ethnic group',
];

export const ethnicGroups = [
  'Indian',
  'Pakistani',
  'Bangladeshi',
  'Chinese',
  'Any other Asian background',
  'Caribbean',
  'African',
  'Any other Black, Black British, or Caribbean background',
  'White and Black Caribbean',
  'White and Black African',
  'White and Asian',
  'Any other Mixed or multiple ethnic background',
  'English, Welsh, Scottish, Northern Irish or British',
  'Irish',
  'Gypsy or Irish Traveller',
  'Roma',
  'Any other White background',
  'Arab',
  'Any other ethnic group',
];
